services:
  - type: web
    name: Rate-OCR
    env: node
    plan: starter
    repo: https://github.com/OpenPecha/Rate-OCR.git
    branch: main
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: Rate-OCR-pg
          property: connectionString

databases:
  - name: Rate-OCR-pg
    plan: free